# vim: set autoindent expandtab shiftwidth=2 softtabstop=2
#
---

azs:
- name: az1
  cloud_properties:
    availability_zone: ((aws_availability_zone1))
- name: az2
  cloud_properties:
    availability_zone: ((aws_availability_zone2))
#  cloud_properties:
#     availability_zone: ((az3))
#  name: az3

networks:
- name: cf_private
  type: manual
  subnets:
  - range: ((private_cidr))
    gateway: ((private_default_route))
    dns: [((vpc_dns_ip))]
    az: az1
    reserved: ["((private_cidr_prefix)).1 - ((private_cidr_prefix)).10"]
    static: ["((private_cidr_prefix)).200 - ((private_cidr_prefix)).245"]
    cloud_properties:
      subnet: ((private_subnet))
- name: cf_dmz
  type: manual
  subnets:
  - range: ((dmz_cidr))
    gateway: ((dmz_default_route))
    dns: [((vpc_dns_ip))]
    az: az1
    reserved: ["((dmz_cidr_prefix)).1 - ((dmz_cidr_prefix)).10"]
    static: ["((dmz_cidr_prefix)).200 - ((dmz_cidr_prefix)).245"]
    cloud_properties:
      subnet: ((dmz_subnet))
      # AWS outputs an array
      security_groups: ((dmz_security_groups))
- name: cf_rabbitmq_services
  type: manual
  subnets:
  - range: ((rabbitmq_services_cidr))
    gateway: ((rabbitmq_services_default_route))
    dns: [((vpc_dns_ip))]
    az: az1
    reserved: ["((rabbitmq_services_cidr_prefix)).1 - ((rabbitmq_services_cidr_prefix)).10"]
    static: ["((rabbitmq_services_cidr_prefix)).200 - ((rabbitmq_services_cidr_prefix)).245"]
    cloud_properties:
      subnet: ((rabbitmq_services_subnet))
- name: elastic
  type: vip
  cloud_properties: {}

resource_pools:
- name: micro_general
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: t2.micro
- name: small_general
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: t2.small
- name: medium_general
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: t2.medium
- name: large_compute
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: c4.large
- name: large_compute_spot
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: c4.large
    # Ensure this is set to a sensible value
    spot_bid_price: 0.05
- name: large_compute_spot_fallback
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: c4.large
    # Ensure this is set to a sensible value
    spot_bid_price: 0.05
    spot_ondemand_fallback: true
- name: xlarge_compute
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: c4.xlarge
- name: xlarge_compute_spot
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: c4.xlarge
    # Ensure this is set to a sensible value
    spot_bid_price: 0.1
- name: xlarge_compute_spot_fallback
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: c4.xlarge
    # Ensure this is set to a sensible value
    spot_bid_price: 0.1
    spot_ondemand_fallback: true
# Its probably better to use more large instances, and less xlarge instances - the cost is the same, the 
# ram will be virtually the same, ignoring base OS overhead, but the availability will be better
- name: large_ram_large_disk
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: r4.large
    ephemeral_disk:
      size: 80000
- name: large_ram_large_disk_spot
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: r4.large
    ephemeral_disk:
      size: 80000
    # Ensure this is set to a sensible value
    spot_bid_price: 0.05
- name: large_ram_large_disk_spot_fallback
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    ephemeral_disk:
      size: 80000
    instance_type: r4.large
    # Ensure this is set to a sensible value
    spot_bid_price: 0.05
    spot_ondemand_fallback: true
- name: xlarge_ram_large_disk
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    ephemeral_disk:
      size: 160000
    instance_type: r4.xlarge
- name: xlarge_ram_large_disk_spot
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    ephemeral_disk:
      size: 160000
    instance_type: r4.xlarge
    # Ensure this is set to a sensible value
    spot_bid_price: 0.1
- name: xlarge_ram_large_disk_spot_fallback
  network: cf_private
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    ephemeral_disk:
      size: 160000
    instance_type: r4.xlarge
    # Ensure this is set to a sensible value
    spot_bid_price: 0.1
    spot_ondemand_fallback: true

compilation:
  workers: 10
  network: cf_private
  reuse_compilation_vms: true
  az: az1
  cloud_properties:
    # Using large VMs decreases initial deployment time massively
    instance_type: m4.4xlarge
