# vim: set autoindent expandtab shiftwidth=2 softtabstop=2
#
---

azs: ((azs))

networks:
- name: cf_private
  type: manual
  subnets: ((cf_private_subnets))
- name: cf_rabbitmq
  type: manual
  subnets: ((cf_rabbitmq_subnets))

vm_types:
- name: micro_general
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 12288
- name: small_general
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 12288
- name: medium_general
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 12288
- name: large_compute
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 12288
- name: xlarge_compute
  cloud_properties:
    cpu: 4
    ram: 16384
    disk: 12288

compilation:
  workers: 10
  network: cf_private
  reuse_compilation_vms: true
  az: az1
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 12288
    ephemeral_disk:
      size: 160000
